export default [
  {
    id: 4,
    title: "Session Pass",
    men: 500,
    women: 500,
    cardioGym: 500,
    gymOnly: 500,
    admissionFee: 0,
    time: "1 Day",
    description: "Access to a single session for a quick workout.",
    isPopular: false,
  },
  {
    id: 3,
    title: "Monthly Membership",
    men: 5000,
    women: 4000,
    cardioGym: 5000,
    gymOnly: 4000,
    admissionFee: 2000,
    time: "1 Month",
    description: "Pay on a monthly basis for access to gym facilities.",
    isPopular: true,
  },
  {
    id: 2,
    title: "Bi-Annual Membership",
    men: 25000,
    women: 20000,
    cardioGym: 25000,
    gymOnly: 20000,
    admissionFee: 0,
    time: "6 Months",
    description: "Access to our facilities for six months with this package.",
    isPopular: false,
  },
  {
    id: 1,
    title: "Annual Membership",
    men: 48000,
    women: 38000,
    cardioGym: 48000,
    gymOnly: 38000,
    admissionFee: 0,
    time: "1 Year",
    description: "An annual package for a full year of fitness benefits.",
    isPopular: false,
  },
];
