export default [
  {
    id: 4,
    title: "Session Pass",
    men: 500,
    women: 500,
    cardioGym: 500,
    gymOnly: 500,
    admissionFee: 0,
    time: "1 Day",
    description: "Access to a single session for a quick workout.",
    isPopular: false,
  },
  {
    id: 3,
    title: "Monthly Membership",
    men: "5,000",
    women: "4,000",
    cardioGym: "5,000",
    gymOnly: "4,000",
    admissionFee: "2,000",
    time: "1 Month",
    description: "Pay on a monthly basis for access to gym facilities.",
    isPopular: true,
  },
  {
    id: 2,
    title: "Bi-Annual Membership",
    men: "25,000",
    women: "20,000",
    cardioGym: "25,000",
    gymOnly: "20,000",
    admissionFee: 0,
    time: "6 Months",
    description: "Access to our facilities for six months with this package.",
    isPopular: false,
  },
  {
    id: 1,
    title: "Annual Membership",
    men: "48,000",
    women: "38,000",
    cardioGym: "48,000",
    gymOnly: "38,000",
    admissionFee: 0,
    time: "1 Year",
    description: "An annual package for a full year of fitness benefits.",
    isPopular: false,
  },
];
